version: '3.8'

services:
  # Banco de Dados PostgreSQL
  db:
    image: postgres:15
    container_name: clinica_db
    restart: always
    environment:
      POSTGRES_USER: user_clinica
      POSTGRES_PASSWORD: password_clinica
      POSTGRES_DB: clinica_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend Node.js
  backend:
    build: ./backend
    container_name: clinica_backend
    restart: always
    # [STI] For√ßa DNS externo para o Google Sheets funcionar
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=user_clinica
      - DB_PASSWORD=password_clinica
      - DB_NAME=clinica_db
      - DB_PORT=5432
    depends_on:
      - db

  # Frontend Nginx
  frontend:
    image: nginx:alpine
    container_name: clinica_frontend
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  postgres_data: